In [1]:
from qutip.qip.operations import *
from qutip.qip.circuit import QubitCircuit, Gate
from qutip import basis, tensor, sigmax, qeye, Qobj
from qutip.qip.device import Processor, OptPulseProcessor
from  qutip.stochastic import StochasticSolverOptions
import numpy as np

In [13]:
searched_string = '111'
N = len(searched_string)
oracle = np.zeros(shape=(2 ** N, 2 ** N))
for b in range(2 ** N):
    if np.binary_repr(b, N) == searched_string:
        oracle[b, b] = -1
    else:
        oracle[b, b] = 1
print(oracle)

qc = QubitCircuit(N=N, reverse_states=False)

for i in range(N):
    qc.add_gate("SNOT", targets=[i])

dim = []

for i in range(N):
    dim.append(2)

o_and_d_targets = []

for i in range(N):
    o_and_d_targets.append(i)

[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]]


In [14]:
# Oracle Gate
def oracle_gate():
    mat = oracle
    return Qobj(mat, dims=[dim, dim])

In [15]:
#Difusion Gate
def diffusion_gate():
    type(N)
    mat = 2.0 * np.full((2 ** N, 2 ** N), 1 / (2 ** N)) - np.eye(2 ** N)
    return Qobj(mat, dims=[dim, dim])

In [16]:
qc.user_gates = {"ORACLE": oracle_gate,
                 "DIFFUSION" : diffusion_gate}

In [17]:
n_iter = int(np.pi / 4 * np.sqrt(2 ** N))

In [18]:
for i in range(n_iter):
    qc.add_gate("ORACLE", targets=o_and_d_targets)
    
    qc.add_gate("DIFFUSION", targets=o_and_d_targets)

In [19]:
#qc.add_gate("DIFFUSION", targets=[0,1])
#qc.propagators()

In [20]:
#q2.png
U2 = gate_sequence_product(qc.propagators())
type(U2)

qutip.qobj.Qobj

In [21]:
U2.tidyup()

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[-0.08838835  0.44194174  0.44194174  0.26516504  0.44194174  0.26516504
   0.26516504  0.44194174]
 [-0.08838835 -0.26516504  0.44194174 -0.44194174  0.44194174 -0.44194174
   0.26516504 -0.26516504]
 [-0.08838835  0.44194174 -0.26516504 -0.44194174  0.44194174  0.26516504
  -0.44194174 -0.26516504]
 [-0.08838835 -0.26516504 -0.26516504  0.26516504  0.44194174 -0.44194174
  -0.44194174  0.44194174]
 [-0.08838835  0.44194174  0.44194174  0.26516504 -0.26516504 -0.44194174
  -0.44194174 -0.26516504]
 [-0.08838835 -0.26516504  0.44194174 -0.44194174 -0.26516504  0.26516504
  -0.44194174  0.44194174]
 [-0.08838835  0.44194174 -0.26516504 -0.44194174 -0.26516504 -0.44194174
   0.26516504  0.44194174]
 [ 0.97227182  0.08838835  0.08838835 -0.08838835  0.08838835 -0.08838835
  -0.08838835  0.08838835]]

In [22]:
#qc.type
#sso = StochasticSolverOptions(m_ops = U2)

In [1]:
#psi0 = tensor([basis(2, 0), basis(2, 0), basis(2, 1)])
#processor = Processor(N=N)
#result = processor.run_state(U2)

In [2]:
#v0 = qc.basis(2, 0)

()